config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do  
  
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    devise_for :users
    resources :users
    resources :home, only: [:index, :new, :create]

    root to: 'home#index'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :contact,   :validate => true
  attribute :message
  

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form - CNeryTours Site",
      :to => "info@cnery.pt",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :authenticate_user! 
  before_action :set_locale
  
  private

  def default_url_options
    {locale: I18n.locale}
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def extract_locale
    parsed_locale = params[:locale]
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ?
      parsed_locale.to_sym :
      nil
  end

  def switch_locale(&action)
    logger.debug "* Accept-Language: #{request.env['HTTP_ACCEPT_LANGUAGE']}"
    locale = extract_locale_from_accept_language_header
    logger.debug "* Locale set to '#{locale}'"
    I18n.with_locale(locale, &action)
  end

  private
  def extract_locale_from_accept_language_header
    request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  
=begin  
  require 'mail_form'
  def def new
    @contact=Contact.new
  end

  def def create
    @contact = Contacts.new(contact_attributes)
      if @contact.deliver
        redirect_to new_contact_path: "Thank you"
      else
        flash.now[:error] = "please correct the form"
        render :new  
  end
=end
  require 'mail_form'

  def index
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    
    if @contact.deliver
      #ContactsMailer.general_message(@contact).deliver
      redirect_to new_contact_path, alert: "Thank you..."
      #render :thanks
    else
      flash.now[:error] = "Please correct the form"
      render :new
    end
  end

  def thanks
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user! 

  def index
    @contact = Home.new(params[:home])
  end

  def create
    @contact = Home.new(params[:home])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize Home object for cleared form
        @contact = Home.new
        format.html { render 'index'}
        format.js   { flash.now[:success] = @message = "Thank you for your message. I'll get back to you soon!" }
      else
        format.html { render 'index' }
        format.js   { flash.now[:error] = @message = "Message did not send." }
      end
    end
  end

  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<%="New contact"%>

app/views/home/_contact_form.html.erb
<section id="contact" class="block contact-block" style="padding-top: 80px; margin-top: -10px;">
  
  <div class="title">
    <%=t('Contact.title')%>
    <h2><div class="subtitle"><%=t('Contact.subtitle')%></div></h2>
	</div>

  <%= form_for @contact, url: home_index_path, remote: true do |f| %>
    <div class="row">

      <div class="col-sm-4">
        <div class="form-group">
          <%= f.text_field  :name, required: true, class: "contact-form-text-area",
            placeholder: t('Contact.input_name')%></br>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="form-group">
          <%= f.text_field :email, required: true, class: "contact-form-text-area",
            placeholder: t('Contact.input_email')%></br>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="form-group">
          <%= f.text_field :contact, required: true, class: "contact-form-text-area",
            placeholder: t('Contact.input_number')%></br>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-text-area",
            placeholder: t('Contact.input_message') %></br>
        </div>
      </div>
    </div>
    <div class="btn-holder">
      <%= f.submit 'Send Message', class: 'btn btn-primary' %>
    </div>
  <% end %>
  <div class="col-md-6" id="flash-message">
    <%= render 'flash' %>
  </div>

  <div class="google-map">
    <iframe
      src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d66954.59251732899!2d-9.226985941515588!3d38.731559466174424!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd1ecdd0239b98cd%3A0xb8ed6940fcd91366!2sC.%20NERY%20TOURS!5e0!3m2!1spt-PT!2spt!4v1619393255558!5m2!1spt-PT!2spt"
      allowfullscreen>
    </iframe>
	</div>
				<div class="container-fluid">
					<div class="contact-info">
						<ul>
							<li><i class="fas fa-envelope"></i> info@cnery.pt</li>
							<li><i class="fas fa-phone"></i> +351 - 925-340-094</li>
							<li><i class="fas fa-map-marker-alt"></i> Lisbon, Portugal</li>
						</ul>
					</div>
				</div>

</section>

app/views/home/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/home/create.js.erb
console.log("This is the create.js.erb file");
// Render flash message
$('#contact').html("<%= j render 'contact_form' %>");
$('#flash-message').html("<%= j render 'flash' %>").delay(3000).fadeOut(4000);

app/views/home/index.html.erb
<div style ="height: 50px"></div>
<!--<h1><%= t('hello') %></h1>-->
<%= render 'shared/navbar' %>
<%= render 'shared/carousel' %>
<%= render 'shared/services' %>
<%= render 'shared/about' %>
<%= render 'contact_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cnerytoursv01</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">
    <link href="fm.selector.jquery.css" rel="stylesheet"/>
  </head>

  <body data-spy="scroll" data-target=".fixed-top">
    <%= render 'shared/navbar' %>
    
    <%= render 'shared/flashes' %>
   
    <%= yield %>
  </body>
</html>

app/views/layouts/contact.html.erb
<%="Contact page"%>

app/views/shared/_about.html.erb
<section id="about" style="padding-top: 30px; margin-top: -10px;">
  
	<div class="jumbotron jumbotron-fluid text-center mt-5 mb-5">
  <div class="container">
    <div class="row">

      <div class=" col-12 pb-4">
        <h1 class="title"><%=t('About.title')%></h1>
      </div>

      <div class="col-1" id="logo">
        <%= image_tag "CNeryToursLogo.png", class:"display-4", alt: "CNery Tours"%>
      </div>
      
    </div>
      <p class="lead"><%=t('About.text1')%></p>
      <p class="lead"><%=t('About.text2')%></p>
      <p class="lead"><%=t('About.text3')%></p>
      <p class="lead"><%=t('About.text4')%></p>
      <p class="lead"><%=t('About.text5')%></p>
    </div>
  </div>
</section>

app/views/shared/_carousel.html.erb
<div id="home" class="carousel slide" data-ride="carousel" style="padding-top: 50px; margin-top: -10px;">
  <div class="carousel-indicators">
    <li data-target="#carouselExampleControls" data-slide-to="0"> 
    <li data-target="#carouselExampleControls" data-slide-to="1">
    <li data-target="#carouselExampleControls" data-slide-to="2">
    <li data-target="#carouselExampleControls" data-slide-to="3">
    <li data-target="#carouselExampleControls" data-slide-to="4">
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "carousel/CNeryTours-Home-Carousel-01.jpg", alt: "First slide",  class: "d-block w-100"%>   
    </div>
    <div class="carousel-item">
      <%= image_tag "carousel/CNeryTours-Home-Carousel-02.jpg", alt: "Second slide",  class: "d-block w-100"%>
    </div>
    <div class="carousel-item">
      <%= image_tag "carousel/CNeryTours-Home-Carousel-03.jpg", alt: "Third slide",  class: "d-block w-100"%>
    </div>
    <div class="carousel-item">
      <%= image_tag "carousel/CNeryTours-Home-Carousel-04.jpg", alt: "Third slide",  class: "d-block w-100"%>
    </div>
    <div class="carousel-item">
      <%= image_tag "carousel/CNeryTours-Home-Carousel-05.jpg", alt: "Third slide",  class: "d-block w-100"%>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_contact_form.html.erb
<section id="contact" class="block contact-block" style="padding-top: 80px; margin-top: -10px;">
  
  <div class="title">
    <%=t('Contact.title')%>
    <h2><div class="subtitle"><%=t('Contact.subtitle')%></div></h2>
	</div>

  <%= form_for @contact, url: home_index_path, remote: true do |f| %>
    <div class="row">

      <div class="col-sm-4">
        <div class="form-group">
          <%= f.text_field  :name, required: true, class: "contact-form-text-area",
            placeholder: t('Contact.input_name')%></br>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="form-group">
          <%= f.text_field :email, required: true, class: "contact-form-text-area",
            placeholder: t('Contact.input_email')%></br>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="form-group">
          <%= f.text_field :contact, required: true, class: "contact-form-text-area",
            placeholder: t('Contact.input_number')%></br>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-text-area",
            placeholder: t('Contact.input_message') %></br>
        </div>
      </div>
    </div>
    <div class="btn-holder">
      <%= f.submit 'Send Message', class: 'btn btn-primary' %>
    </div>
  <% end %>
  <div class="col-md-6" id="flash-message">
    <%= render 'shared/flash' %>
  </div>

  <div class="google-map">
    <iframe
      src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d38958.14907668316!2d-9.154197058454331!3d38.7319511127191!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd193301e6b1d677%3A0x971868cd2a4f609a!2sSPR%20Tours%20-%20Tours%20%26%20Transfers%20in%20Lisbon%2C%20Sintra%2C%20Cascais%2C%20F%C3%A1tima!5e0!3m2!1spt-PT!2spt!4v1617967594673!5m2!1spt-PT!2spt"
      allowfullscreen>
    </iframe>
	</div>
				<div class="container-fluid">
					<div class="contact-info">
						<ul>
							<li><i class="fas fa-envelope"></i> info@cnery.pt</li>
							<li><i class="fas fa-phone"></i> +351 - 925-340-094</li>
							<li><i class="fas fa-map-marker-alt"></i> Lisbon, Portugal</li>
						</ul>
					</div>
				</div>

</section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-md navbar-light fixed-top navbar-cnery">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "CNeryToursLogo.png", alt: "CNery Tours"%>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" 
  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item ">
  					<a class="nav-link js-scroll-trigger" href="/#home" ><%=t('Menu.Home')%></a>
        </li>
        <li class="nav-item ">
  					<a class="nav-link js-scroll-trigger" href="#tours"><%=t('Menu.Tours')%></a>
        </li>
        <li class="nav-item ">
          <a class="nav-link js-scroll-trigger" href="#services"><%=t('Menu.Services')%></a>
        </li>
        <li class="nav-item ">
          <a class="nav-link js-scroll-trigger" href="#about"><%=t('Menu.About')%></a>
        </li>
        <li class="nav-item ">
          <a class="nav-link js-scroll-trigger" href="#contact"><%=t('Menu.Contact')%></a>
        </li>
         

        <li class="nav-item dropdown" id="Nav2">
            <a class="nav-link dropdown-toggle" href="#" role="button" 
            id="dropdown09"  data-toggle="dropdown"  style="width: 150px;" >
            <%= raw t('Menu.flag')%></span><%=t('Menu.language')%></a>
            <div class="dropdown-menu" aria-labelledby="dropdown09" id="aaa" hover: {display: block} data-turbolinks="false">
                
                <%= link_to  home_index_path(:locale => t('Menu.href1')), :class => "dropdown-item" do %>
                  <%= raw t('Menu.flag1')%></span ><%=t('Menu.language1')%></a>
                <%end%>
                <%= link_to  home_index_path(:locale => t('Menu.href2')), :class => "dropdown-item" do %>
                  <%= raw t('Menu.flag2')%></span ><%=t('Menu.language2')%></a>
                <%end%>
                <%= link_to  home_index_path(:locale => t('Menu.href3')), :class => "dropdown-item" do %>
                  <%= raw t('Menu.flag3')%></span ><%=t('Menu.language3')%></a>
                <%end%>
            
            </div>
        </li>

        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>

        <li class="nav-item dropdown">
          <%= image_tag "Andre01.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item ">
            <%= link_to t('Menu.Home'), home_index_path( anchor: 'home'), class: "nav-link js-scroll-trigger" %>
        </li>
        <li class="nav-item ">
          <%= link_to t('Menu.Tours'), home_index_path(anchor: 'tours'), class: "nav-link js-scroll-trigger" %>
        </li>
        <li class="nav-item ">
          <%= link_to t('Menu.Services'), home_index_path(anchor: 'services'), class: "nav-link js-scroll-trigger" %>
        </li>
        <li class="nav-item ">
          <%= link_to t('Menu.About'), home_index_path(anchor: 'about'), class: "nav-link js-scroll-trigger" %>
        </li>
        <li class="nav-item ">
          <%= link_to t('Menu.Contact'), home_index_path(anchor: 'contact'), class: "nav-link js-scroll-trigger" %>
        </li>
         

        <li class="nav-item dropdown" id="Nav2">
            <a class="nav-link dropdown-toggle" href="#" role="button" 
            id="dropdown09"  data-toggle="dropdown"  style="width: 150px;" >
            <%= raw t('Menu.flag')%></span><%=t('Menu.language')%></a>
            <div class="dropdown-menu" aria-labelledby="dropdown09" id="aaa" hover: {display: block} data-turbolinks="false">
                
                <%= link_to  home_index_path(:locale => t('Menu.href1')), :class => "dropdown-item" do %>
                  <%= raw t('Menu.flag1')%></span ><%=t('Menu.language1')%></a>
                <%end%>
                <%= link_to  home_index_path(:locale => t('Menu.href2')), :class => "dropdown-item" do %>
                  <%= raw t('Menu.flag2')%></span ><%=t('Menu.language2')%></a>
                <%end%>
                <%= link_to  home_index_path(:locale => t('Menu.href3')), :class => "dropdown-item" do %>
                  <%= raw t('Menu.flag3')%></span ><%=t('Menu.language3')%></a>
                <%end%>

            </div>
        </li>

        
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_newcontact.html.erb
<!-- contact block -->
			<section id="contact" class="block contact-block" style="padding-top: 80px; margin-top: -10px;">
				<div class="title-holder">
					<h2><%=t('Contact.title')%></h2>
					<div class="subtitle"><%=t('Contact.subtitle')%></div>
				</div>
				<div class="container-fluid">
					<!--<form class="contact-form" >-->
					<%= form_for @contact, class: "contact-form", url: home_index_path, remote: true do |f| %>
						<div class="row">
							<div class="col-sm-4">
								<div class="form-group">
									<%= f.text_field  :name, required: true, class: "contact-form-text-area" %></br>
									<!--<%=raw t('Contact.input_name')%>
                  <input type="text" placeholder="Enter your Full Name" required>-->
								</div>
							</div>
							<div class="col-sm-4">
								<div class="form-group">
                  <%=raw t('Contact.input_email')%>
									<!--<input type="text" placeholder="Enter your Email Address" required>-->
								</div>
							</div>
							<div class="col-sm-4">
								<div class="form-group">
                  <%=raw t('Contact.input_number')%> 
									<!--<input type="text" placeholder="Enter your Contact Number">-->
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-sm-12">
								<div class="form-group">
                  <%=raw t('Contact.input_message')%></textarea>
                  <!--<textarea placeholder="Enter your Message" required></textarea>-->
								</div>
							</div>
						</div>
						<div class="btn-holder">
							<button class="btn btn-primary">Submit</button>
						</div>
					</form>
				</div>
				<div class="google-map">
					<iframe
						src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d14048.211570060965!2d-0.1228208876550775!3d51.505942908931324!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2suk!4v1481805868782"
						allowfullscreen></iframe>
				</div>
				<div class="container-fluid">
					<div class="contact-info">
						<ul>
							<li><i class="fas fa-envelope"></i> info@cnery.pt</li>
							<li><i class="fas fa-phone"></i> +351 - 925-340-094</li>
							<li><i class="fas fa-map-marker-alt"></i> Lisbon, Portugal</li>
						</ul>
					</div>
				</div>
			</section>

app/views/shared/_services.html.erb
<section id="services" style="padding-top: 80px; margin-top: -10px;">
	<div class="container-fluid mt=5 mb-5" id="service_container">
	<div class="row">
		<div class="col-md-12 col-sm-" id="Services-Header">
			<h1 class="title text-center" id="Services-Header"><%=t('Menu.Services')%></h1>
		</div>
	</div>
	
		<div class="row">

			<div class="col-lg-3 col-md-6 col-sm-12">
				<div class="card h-100">
          <%= image_tag "services/CNeryTours-Services-Van.jpg", alt: "Van Tours",  class: "card-img-top"%>
					<div class="card-body">
						<h1><%=t('Services.title-1')%></h1>
						<p></p>
						<p><%=t('Services.text-1')%></p>
					</div>
				</div>
			</div>
			
			<div class="col-lg-3 col-md-6 col-sm-12">
				<div class="card h-100">
					<%= image_tag "services/CNeryTours-Services-TukTuk-02.jpg", alt: "Tuk Tuk Tours",  class: "card-img-top"%>
					<div class="card-body">
						<h1><%=t('Services.title-2')%></h1>
							<p></p>
						<p><%=t('Services.text-2')%></p>
					</div>
				</div>
			</div>
			
			<div class="col-lg-3 col-md-6 col-sm-12">
				<div class="card h-100">
					<%= image_tag "services/CNeryTours-Services-Regular.jpg", alt: "Tuk Tuk Tours",  class: "card-img-top"%>
					<div class="card-body">
						<h1><%=t('Services.title-3')%></h1>
							<p></p>
						<p><%=t('Services.text-3')%></p>
					</div>
				</div>
			</div>

			<div class="col-lg-3 col-md-6 col-sm-12">
				<div class="card h-100">
					<%= image_tag "services/CNeryTours-Services-Privat.jpg", alt: "Tuk Tuk Tours",  class: "card-img-top"%>
					<div class="card-body">
						<h1><%=t('Services.title-4')%></h1>
							<p></p>
						<p><%=t('Services.text-4')%></p>
					</div>
				</div>
			</div>
      
      <div class="col-md-12 col-sm-" >
			<h1 class="text-center text-success mb-4"></h1>
		</div>

		</div>

	</div>
</section>